config/routes.rb
Care247::Application.routes.draw do

    get "desks/new"
    get "desks/create"
    get "desks/update"
    get "desks/destroy"
    get "desks/show"

    root to: "static_pages#home"
    resources :users do
        resources :desks, only: [:new, :create]
    end

    resources :desks, only: [:show, :update, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
    resources :requests, only: [:show, :update, :destroy, :index]


    get "static_pages/home"
    get "/pricing", to: "static_pages#pricing"
    get "/about", to: "static_pages#about"
    get "/signin", to: "sessions#new"
    get "/edit_desk/:id", to: "desks#edit", as: :edit_desk

    match "/signout", to: "sessions#destroy", via: :delete
    match "/answer_request/:id", to: "requests#answer_request", via: :post, as: :answer_request
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  street         :string(255)
#  city           :string(255)
#  zip_code       :string(255)
#  country        :string(255)
#  dic            :string(255)
#  email          :string(255)
#  password_hash  :string(255)
#  password_salt  :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  phone          :string(255)
#  admin          :boolean
#  ic             :string(255)
#  remember_token :string(255)
#

class User < ActiveRecord::Base

	has_many :desks, dependent: :destroy

	# Regexp for email format validation. Only emails with numbers, letters, "-" and "." pass
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	# Variable for saving users input from form and then creating password_hash and password_salt from it. Not saved to database.
	attr_accessor :password

	before_save :encrypt_password, on: :create
	before_save :create_remember_token

	validates :name, presence: true
	validates :email, presence: true, format:{with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	validates :password, presence: true, on: :create

# => Resolve these
#	validates :remember_token, presence: true
#	validates :phone, numericality: true
#	validates :ic, numericality: true

	

	def self.authenticate(email, password)
		if user = User.find_by_email(email)
			if BCrypt::Engine.hash_secret(password, user.password_salt) == user.password_hash
				user
			else
				nil
			end
		end
	end

	private

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(@password, password_salt)
		end
	end

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_filter :admin_user, only: [:index, :destroy]
	before_filter :correct_user, only: [:show, :update]

	layout "backend", only: [:show]

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user].permit(:name, :email, :password))
		if @user.save
			
			MyMailer.welcome_email(@user).deliver

			redirect_to @user
			flash[:success] = "Byl jste uspesne zaregistrovan"
			# session things
			# ..
			#..
		else
			flash[:error] = "Bohuzel se pri registraci neco zvrtlo, zkuste to znovu."
			render :new
		end
	end

	def show
		# I'm using "find_by_id" beause simple "find" returns error RecordNotFound and doesn't execute the if-else when queriing qith non-existant id 
		if @user = User.find_by_id(params[:id])
			@desks = @user.desks.all
			render :show
		else
			redirect_to root_url
		end
	end

	def update
		# "find_by_id" - stejne jako u show
		if @user = User.find(params[:id])
			if @user.update_attributes(params[:user].permit(:name, :email, :street, :city, :zip_code, :country, :dic, :ic, :phone))
				flash[:success] = "Uspesne jste upravil udaje"
				sign_in @user
				redirect_to @user
			else
				flash[:warning] = "Udaje se nepodarilo ulozit"
				render :show
			end
		else
			redirect_to root_url
		end
	end

	def index
		@users = User.all
	end

	def destroy
		if User.find(params[:id]).destroy
			flash[:success] = "Successfully destroyed."
			redirect_to users_url
		else
			flash[:error] = "something went wrong and user wasn't deleted..."
			redirect_to users_url
		end
	end

	private

	def admin_user
		redirect_to root_url unless current_user.admin?
	end

	def correct_user
		redirect_to root_url unless User.find(params[:id]) == current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_eshop_tabs.html.erb
<div class="navbar">
	<div class="navbar-inner" id="desk-tabs">
		<ul class="nav">
			<li><%= link_to "Všechny tickety", requests_path %></li>
			<% current_users_desks.each do |d| %>
				<li><%= link_to d.name, desk_url(d) %></li>
			<% end %>
			<li class="li-pull-right"><%= link_to "Zalozit novou podporu", new_user_desk_url(current_user.id), class: "new-desk" %></li>
		</ul>
	</div>
</div>

app/views/users/index.html.erb
<ul>
	<% @users.each do |u| %>
		<li><%= u.name %> | <%= link_to "Delete", user_path(u), method: "delete" %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
<div class="row">
	<div class="span4">
		<h3>Založte nový účet prosím</h3>
		<%= form_for @user do |u| %>
			<p>Jméno</p>
			<%= u.text_field :name %>
			<p>Email</p>
			<%= u.text_field :email %>
			<p>Heslo</p>
			<%= u.text_field :password %>
			<%= u.submit class: "btn", value: "Založit účet" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h2>Uzivatelske udaje</h2>
<div class="row-fluid">
	<div class="span4">
		<h4>Kontaktni udaje:</h4>
		<%= form_for @user, url: user_path(@user) do |u| %>
			<%= u.label :Jméno %>
			<%= u.text_field :name, value: @user.name %>
			<%= u.label :Email %>
			<%= u.text_field :email, value: @user.email %>
			<%= u.label :Telefon %>
			<%= u.text_field :phone, value: @user.phone %>
	</div>
	<div class="span4">
		<h4>Adresa:</h4>
			<%= u.label :Ulice %>
			<%= u.text_field :street, value: @user.street %>
			<%= u.label :Město %>
			<%= u.text_field :city, value: @user.city %>
			<%= u.label :PSČ %>
			<%= u.text_field :zip_code, value: @user.ic %>
	</div>
	<div class="span4">
		<h4>Fakturacni udaje:</h4>
			<%= u.label :IČ %>
			<%= u.text_field :ic, value: @user.ic %>
			<%= u.label :DIČ %>
			<%= u.text_field :dic, value: @user.dic %>
	</div>
	<div class="span12">
		<%= u.submit "Uložit údaje", class: "btn btn-success" %>
		<% end %>
	</div>
</div>