config/routes.rb
Care247::Application.routes.draw do

    get "desks/new"
    get "desks/create"
    get "desks/update"
    get "desks/destroy"
    get "desks/show"

    root to: "static_pages#home"
    resources :users do
        resources :desks, only: [:new, :create]
    end

    resources :desks, only: [:show, :update, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
    resources :requests, only: [:show, :update, :destroy, :index]


    get "static_pages/home"
    get "/pricing", to: "static_pages#pricing"
    get "/about", to: "static_pages#about"
    get "/signin", to: "sessions#new"
    get "/edit_desk/:id", to: "desks#edit", as: :edit_desk

    match "/signout", to: "sessions#destroy", via: :delete
    match "/answer_request/:id", to: "requests#answer_request", via: :post, as: :answer_request
end

app/models/desk.rb
# == Schema Information
#
# Table name: desks
#
#  id                  :integer          not null, primary key
#  name                :string(255)      not null
#  notificate          :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  resolved_requests   :integer          default(0)
#  unresolved_requests :integer          default(0)
#  user_id             :integer          not null
#  desks_mailbox       :string(255)
#

class Desk < ActiveRecord::Base

	belongs_to :user
	has_many :requests, dependent: :destroy

	validates :name, presence: true
	validates :user_id, presence: true
	validates :desks_mailbox, presence: true
	validates_numericality_of :resolved_requests, greater_than: -1
	validates_numericality_of :unresolved_requests, greater_than: -1
	
	def resolved_requests
		self.requests.where status_flag: 1
	end

	def unresolved_requests
		self.requests.where status_flag: 0
	end
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController

    layout "backend"

    before_filter :signed_in_user
    before_filter :correct_user, only: [:edit, :update, :destroy, :show]

    def new
        @desk = Desk.new
    end

    def create
        @desk = current_user.desks.build(params[:desk].permit(:name, :notificate, :desks_mailbox))
        if @desk.save
            flash[:success] = "Podpora byla uspesne vytorena"
            redirect_to @desk
        else
            flash[:error] = "Podporu se nepodarilo vytvorit, zkuste to prosim znovu"
            render :new
        end
    end

    def edit
        redirect_to root_url unless @desk = Desk.find(params[:id])
    end

    def update
        if @desk = Desk.find(params[:id])
            if @desk.update_attributes(params[:desk].permit(:name, :notificate, :desks_mailbox))
                flash[:success] = "Udaje byly uspesne zmeneny"
                redirect_to @desk
            else
                flash[:error] = "Udaje se nepodarilo ulozit, zkuiste to znovu."
                render :show
            end
        end
    end

    def destroy
        if @desk = Desk.find(params[:id])
            @desk.destroy
            redirect_to current_user
        else
            redirect_to root_url
        end
    end

    def show
        if @desk = Desk.find(params[:id])
            @resolved_requests = @desk.resolved_requests
            @unresolved_requests = @desk.unresolved_requests
            render :show
        else
            redirect_to root_url
        end                
    end

    private

    def signed_in_user
        redirect_to root_url unless signed_in?
    end

    def correct_user
        redirect_to root_url unless Desk.find(params[:id]).user_id == current_user.id
    end
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/views/desks/edit.html.erb
<div class="row">
	<div class="span6">
		<%= form_for @desk do |d| %>
			<%= d.label :Název %>
			<%= d.text_field :name %>
			<%= d.label :Email %>
			<%= d.text_field :desks_mailbox %>
			<%= d.label :Upozorňovat %>
			<%= d.text_field :notificate %>
			<br>
			<%= d.submit "Ulozit udaje", class: "btn btn-success" %>
		<% end %>
		<%= link_to "Smazat podporu", desk_path(@desk), method: "delete" %>
	</div>
</div>

app/views/desks/new.html.erb
<h1>Vytvoření nové podpory</h1>

<%= form_for @desk, url: user_desks_path do |d| %>
	<%= d.label :Název %>
	<%= d.text_field :name %>
	<%= d.label :Email %>
	<%= d.text_field :desks_mailbox %>
	<%= d.label :Upozorňovat %>
	<%= d.text_field :notificate %>
	<br>
	<%= d.submit "Vytvořit podporu", class: "btn btn-success" %>
<% end %>

app/views/desks/show.html.erb
<div class="row-fluid">
	<div class="span12">

		<div class="widget">
		  <div class="widget-head">
		    <div class="pull-left">Nevyřízené tickety</div> 
		    <div class="clearfix"></div>
		  </div>
	    
	    <div class="widget-content">
	      
	      <table class="table table-striped table-bordered table-hover">
	        <thead>
	          <tr>
	            <th>Předmět</th>
							<th>Číslo ticketu</th>
							<th>Odesílatel</th>
							<th>Přijato - Doba od přijetí</th>
							<th>Akce</th>
	          </tr>
	        </thead>
	        <tbody>
						<% @unresolved_requests.each do |r| %>
							<tr class="hover-row">
								<td><%= link_to r.subject, request_url(r.id) %></td>
								<td><%= r.id %></td>
								<td><%= r.from %></td>
								<td><%= r.created_at.to_formatted_s :czech_time_date %> | <%= time_difference r.created_at %></td>
								<td><%= link_to "Smazat", request_url(r.id), class: "btn btn-danger", method: "delete" %></td>
							</tr>
						<% end %>                                                                       
	        </tbody>
	      </table>
	    
	      <div class="widget-foot">
	        <div class="clearfix"></div> 
	      </div>
	    
	    </div>
		</div>

	</div>
</div>


<div class="row-fluid">
	<div class="span12">

		<div class="widget">
		  <div class="widget-head">
		    <div class="pull-left">Vyřízené tickety</div>
		    <div class="widget-icons pull-right">
		      <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
		      <a href="#" class="wclose"><i class="icon-remove"></i></a>
		    </div>  
		    <div class="clearfix"></div>
		  </div>
	    
	    <div class="widget-content">
	      
	      <table class="table table-striped table-bordered table-hover">
	        <thead>
	          <tr>
	            <th>Předmět</th>
							<th>Číslo ticketu</th>
							<th>Odesílatel</th>
							<th>Přijato - Doba od přijetí</th>
							<th>Akce</th>
	          </tr>
	        </thead>
	        <tbody>
						<% @resolved_requests.each do |r| %>
							<tr>
								<td><%= link_to r.subject, request_url(r.id) %></td>
								<td><%= r.id %></td>
								<td><%= r.from %></td>
								<td><%= r.created_at.to_formatted_s :czech_time_date %> | <%= time_difference r.created_at %></td>
								<td><%= link_to "Smazat", request_url(r.id), class: "btn btn-danger", method: "delete" %></td>
							</tr>  
						<% end %>                                                                        
	        </tbody>
	      </table>
	    
	      <div class="widget-foot">
	        <div class="clearfix"></div> 
	      </div>
	    
	    </div>
		</div>

	</div>
</div>