config/routes.rb
Care247::Application.routes.draw do

    get "desks/new"
    get "desks/create"
    get "desks/update"
    get "desks/destroy"
    get "desks/show"

    root to: "static_pages#home"
    resources :users do
        resources :desks, only: [:new, :create]
    end

    resources :desks, only: [:show, :update, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
    resources :requests, only: [:show, :update, :destroy, :index]


    get "static_pages/home"
    get "/pricing", to: "static_pages#pricing"
    get "/about", to: "static_pages#about"
    get "/signin", to: "sessions#new"
    get "/edit_desk/:id", to: "desks#edit", as: :edit_desk

    match "/signout", to: "sessions#destroy", via: :delete
    match "/answer_request/:id", to: "requests#answer_request", via: :post, as: :answer_request
end

app/views/layouts/_content_backend.html.erb
<div class="content">

  <%= render 'layouts/sidebar_backend' %>

  <%= render 'layouts/mainbar_backend' %>

  <div class="clearfix"></div>

</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>© Care247 | info@care247 | Developed by Masa331</small>
</div>

app/views/layouts/_footer_backend.html.erb
<footer>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
            <!-- Copyright info -->
            <p class="copy">Copyright &copy; 2013 | <a href="#">Care247</a> </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header">
	<ul class="nav nav-pills pull-right">
		<% if signed_in? %>
			<li><%= link_to current_user.name, user_path(current_user) %></li>
			<li><%= link_to "Odhlasit", signout_path, method: "delete" %></li>

			<li><%= link_to "Index", users_path if current_user.admin? %></li>
		<% else %>
			<li><%= link_to "Přihlásit se", new_session_url %></strong>
		<% end %>
		<li><%= link_to "Domů", root_path %></li>
		<li><%= link_to "O Care247", about_path %></li>
		<li><%= link_to "Ceník", pricing_path %></li>
	</ul>
	<h3 class="muted">Care247</h3>

</div>

app/views/layouts/_header_backend.html.erb
<header>
    <div class="container-fluid">
      <div class="row-fluid">

        <!-- Logo section -->
        <div class="span4">
          <!-- Logo. -->
          <div class="logo">
            <h1><a href="#">Care<span class="bold">247</span></a></h1>
            <p class="meta">something goes in meta area</p>
          </div>
          <!-- Logo ends -->
        </div>

      </div>
    </div>
  </header>

app/views/layouts/_mainbar_backend.html.erb
<div class="mainbar">

  <!-- Page heading -->
  <div class="page-head">
   
    <h2 class="pull-left">Dashboard</h2>

    <div class="clearfix"></div>

  </div>
  <!-- Page heading ends -->



  <!-- Page content -->

  <div class="matter">
    <div class="container-fluid">

      <%= yield %>

    </div>
  </div>

</div>

app/views/layouts/_sidebar_backend.html.erb
<div class="sidebar">
  <ul id="nav">
	  <li>
	  	<%= link_to requests_path do %>
	    	<i class="icon-list-alt"></i> Vsechny tickety
	    <% end %>
  	</li> 
	  <% current_users_desks.each do |d| %>
			<li>
		  	<%= link_to desk_path(d) do %>
		    	<span><%= d.name %></span>
		    <% end %>
  		</li>
		<% end %>
		<li>
		  	<%= link_to new_user_desk_url(current_user.id) do %>
		    	<span>Zalozit podporu</span>
		    <% end %>
		</li>
    <li>
	  	<%= link_to user_path(current_user) do %>
	    	<i class="icon-wrench"></i> Nastaveni uctu
	    <% end %>
  	</li>
  	<li>
	  	<%= link_to signout_path, method: "delete" do %>
	    	<i class="icon-off"></i> Odhlasit
	    <% end %>
  	</li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Care247</title>

	<!-- Importing Twitter Bootstrap and jQuery from CDN's for faster page loading -->

	<%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.no-responsive.no-icons.min.css" %>

	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"%>
	<%= stylesheet_link_tag "custom", media: "all", "data-turbolinks-track" => true %>



	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end %>

		<%= yield %>

		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <!-- Title and other stuffs -->
  <title>Login</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="">

  <!-- Stylesheets -->
  
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "font-awesome", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "bootstrap-responsive", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "style", media: "all", "data-turbolinks-track" => true %>

  <!-- JS -->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery-ui-1.9.2.custom.min", "data-turbolinks-track" => true %>
  

  <%= csrf_meta_tags %>

  <!-- HTML5 Support for IE -->
  <!--[if lt IE 9]>
  <script src="js/html5shim.js"></script>
  <![endif]-->

  <!-- Favicon -->
  <link rel="shortcut icon" href="img/favicon/favicon.png">
</head>

<body>

<%= render 'layouts/header_backend' %>

<%= render 'layouts/content_backend' %>

<%= render 'layouts/footer_backend' %>
  
</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <!-- Title and other stuffs -->
  <title>Login</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="">

  <!-- Stylesheets -->
  
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "font-awesome", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "bootstrap-responsive", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "style", media: "all", "data-turbolinks-track" => true %>

  <!-- JS -->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery", "data-turbolinks-track" => true %>

  <!-- HTML5 Support for IE -->
  <!--[if lt IE 9]>
  <script src="js/html5shim.js"></script>
  <![endif]-->

  <!-- Favicon -->
  <link rel="shortcut icon" href="img/favicon/favicon.png">
</head>

<body>

<!-- Form area -->
<div class="admin-form">
  <div class="container-fluid">

    <div class="row-fluid">
      <div class="span12">
        <!-- Widget starts -->
            
        <%= yield %>

      </div>
    </div>
  </div> 
</div>
  

</body>
</html>

app/views/layouts/signed_in.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Care247</title>

	<!-- Importing Twitter Bootstrap and jQuery from CDN's for faster page loading -->

	<%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.no-responsive.no-icons.min.css" %>

	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"%>
	<%= stylesheet_link_tag "custom", media: "all", "data-turbolinks-track" => true %>
	

	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		
		<%= render 'users/eshop_tabs' %>
		
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end %>

		<%= yield %>

		<%= render 'layouts/footer' %>
	</div>
</body>
</html>